// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApfseSGxtG0XekkIlVxjLHhwA8fQpHTM',
    appId: '1:474860078400:web:4bc86aa1019a29fd33e6a5',
    messagingSenderId: '474860078400',
    projectId: 'emergencyapp-7e179',
    authDomain: 'emergencyapp-7e179.firebaseapp.com',
    storageBucket: 'emergencyapp-7e179.appspot.com',
    measurementId: 'G-BYD8EQH65B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6VK5ptVAZ8KL8AFHMxXw3HHdV-QFHo4',
    appId: '1:474860078400:android:93865b0c8faa298f33e6a5',
    messagingSenderId: '474860078400',
    projectId: 'emergencyapp-7e179',
    storageBucket: 'emergencyapp-7e179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnvxvXOY1BQs_m07WSP0wx4UZA0_3AY6g',
    appId: '1:474860078400:ios:e0ec0172d18e367633e6a5',
    messagingSenderId: '474860078400',
    projectId: 'emergencyapp-7e179',
    storageBucket: 'emergencyapp-7e179.appspot.com',
    iosClientId: '474860078400-pl47qm2ea0knmelnc7gq8q1rv9qhe5go.apps.googleusercontent.com',
    iosBundleId: 'com.example.squip',
  );
}
